
'use client';

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger, DialogClose } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { useState, type FormEvent, useEffect } from "react";
import type { RFI, RfiStatus } from "@/types/rfi";

interface RfiFormProps {
  triggerButton: React.ReactNode;
  mode: 'create' | 'edit';
  projectId: string;
  rfiData?: RFI;
  onSave: (rfi: RFI) => void;
}

const rfiStatuses: RfiStatus[] = ["Open", "In Progress", "Needs Clarification", "Closed"];
const rfiPriorities: RFI['priority'][] = ["Low", "Medium", "High"];

// Mock users for assignee dropdown - in a real app, fetch this
const mockUsers = [
  { id: 'user-alice', name: 'Alice Wonderland' },
  { id: 'user-bob', name: 'Bob The Builder' },
  { id: 'user-charlie', name: 'Charlie Brown' },
  { id: 'user-diana', name: 'Diana Prince' },
];


export function RfiForm({ triggerButton, mode, projectId, rfiData, onSave }: RfiFormProps) {
  const [isOpen, setIsOpen] = useState(false);
  const { toast } = useToast();

  // Form state
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [status, setStatus] = useState<RfiStatus>('Open');
  const [priority, setPriority] = useState<RFI['priority']>('Medium');
  const [assignedToUserId, setAssignedToUserId] = useState<string | undefined>(undefined);
  const [dueDate, setDueDate] = useState('');
  const [tags, setTags] = useState(''); // Comma-separated string

  const resetFormFields = (data?: RFI) => {
    setTitle(data?.title || '');
    setDescription(data?.description || '');
    setStatus(data?.status || 'Open');
    setPriority(data?.priority || 'Medium');
    setAssignedToUserId(data?.assignedToUserId || undefined);
    setDueDate(data?.dueDate ? data.dueDate.split('T')[0] : ''); // Format for date input
    setTags(data?.tags?.join(', ') || '');
  };

  useEffect(() => {
    if (isOpen) {
      if (mode === 'edit' && rfiData) {
        resetFormFields(rfiData);
      } else {
        resetFormFields(); // Reset for create mode
      }
    }
  }, [rfiData, mode, isOpen]);

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();

    if (!title.trim()) {
      toast({ title: "RFI Title Required", description: "Please enter a title for the RFI.", variant: "destructive" });
      return;
    }
    if (!description.trim()) {
      toast({ title: "RFI Description Required", description: "Please enter a description for the RFI.", variant: "destructive" });
      return;
    }
    
    const assignedUser = mockUsers.find(u => u.id === assignedToUserId);

    const newOrUpdatedRfi: Partial<RFI> = {
      id: mode === 'create' ? `rfi-${Date.now()}-${Math.random().toString(16).slice(2,8)}` : rfiData!.id,
      projectId: projectId,
      title: title.trim(),
      description: description.trim(),
      status,
      priority,
      assignedToUserId: assignedToUserId,
      assignedToUserName: assignedUser?.name,
      dueDate: dueDate ? new Date(dueDate).toISOString() : undefined,
      tags: tags.split(',').map(tag => tag.trim()).filter(tag => tag),
      // For create mode, some fields are set by the parent or defaults
      ...(mode === 'create' && {
        // rfiNumber will be generated by parent
        raisedByUserId: 'current-user-id', // Placeholder for actual current user
        raisedByUserName: 'Current User', // Placeholder
        messages: [],
        attachments: [],
      }),
      // For edit mode, merge with existing rfiData if needed, messages/attachments handled separately
      ...(mode === 'edit' && rfiData && {
        messages: rfiData.messages,
        attachments: rfiData.attachments,
        rfiNumber: rfiData.rfiNumber,
        raisedByUserId: rfiData.raisedByUserId,
        raisedByUserName: rfiData.raisedByUserName,
      })
    };

    onSave(newOrUpdatedRfi as RFI); // Cast as RFI, parent will fill in missing parts for create
    toast({ title: mode === 'create' ? "RFI Created" : "RFI Updated", description: `RFI "${newOrUpdatedRfi.title}" has been saved.` });
    setIsOpen(false);
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>{triggerButton}</DialogTrigger>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle className="font-headline">{mode === 'create' ? 'Create New RFI' : `Edit RFI: ${rfiData?.rfiNumber || ''}`}</DialogTitle>
          <DialogDescription>
            {mode === 'create' ? 'Fill in the details to create a new Request for Information.' : 'Update the RFI details.'}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4 max-h-[70vh] overflow-y-auto pr-2">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="rfiTitle" className="text-right">Title</Label>
              <Input id="rfiTitle" value={title} onChange={(e) => setTitle(e.target.value)} className="col-span-3" required />
            </div>
            <div className="grid grid-cols-4 items-start gap-4">
              <Label htmlFor="rfiDescription" className="text-right pt-2">Description</Label>
              <Textarea
                id="rfiDescription"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Provide a detailed description of the information needed..."
                className="col-span-3 min-h-[100px]"
                required
              />
            </div>
             <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="rfiStatus" className="text-right">Status</Label>
              <Select value={status} onValueChange={(value: RfiStatus) => setStatus(value)}>
                <SelectTrigger className="col-span-3">
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  {rfiStatuses.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="rfiPriority" className="text-right">Priority</Label>
              <Select value={priority} onValueChange={(value: RFI['priority']) => setPriority(value)}>
                <SelectTrigger className="col-span-3">
                  <SelectValue placeholder="Select priority" />
                </SelectTrigger>
                <SelectContent>
                  {rfiPriorities.map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="rfiAssignedTo" className="text-right">Assigned To</Label>
              <Select value={assignedToUserId} onValueChange={(value) => setAssignedToUserId(value)}>
                <SelectTrigger className="col-span-3">
                  <SelectValue placeholder="Assign to a user" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="">Unassigned</SelectItem>
                  {mockUsers.map(user => <SelectItem key={user.id} value={user.id}>{user.name}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="rfiDueDate" className="text-right">Due Date</Label>
              <Input id="rfiDueDate" type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} className="col-span-3" />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="rfiTags" className="text-right">Tags</Label>
              <Input id="rfiTags" value={tags} onChange={(e) => setTags(e.target.value)} className="col-span-3" placeholder="e.g., Structural, Electrical, Urgent" />
            </div>
          </div>
          <DialogFooter className="pt-4 border-t mt-2">
            <DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose>
            <Button type="submit" className="bg-primary hover:bg-primary/90">
              {mode === 'create' ? 'Create RFI' : 'Save Changes'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
